(() => {
  'use strict';
  const LEGACY_KEY='ramen-gacha-shops-v1', DB_NAME='ramen-gacha-db-v2', STORE='state', STATE='shops', MAP_USAGE_STATE='google-maps-usage-v1', MAX_PHOTO=300*1024, MAPS_KEY='ramen-gacha-google-maps-key', MAPS_FREE_LIMIT=8000;
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  let shops=[],map,markers=[],selectedPosition=null,selectionMarker=null,detailShopId=null,selectedFilter='all',spinning=false,lastResult=null,pendingPhoto=null,crop=null,cropPointers=new Map(),cropGesture=null,mapsUsage=null,bootPromise=null,mapInitPromise=null,placeSearchTimer=null,placeSearchToken=null,placeSearchSequence=0,placeSearchReady=false;
  const validShop=s=>s&&typeof s.id==='string'&&typeof s.name==='string'&&['visited','unvisited'].includes(s.status)&&Number.isFinite(Number(s.lat))&&Number.isFinite(Number(s.lng));
  const uid=()=>crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(16).slice(2)}`;
  const esc=t=>{const x=document.createElement('div');x.textContent=t||'';return x.innerHTML};
  const date=d=>d?new Date(`${d}T00:00:00`).toLocaleDateString('ja-JP',{year:'numeric',month:'long',day:'numeric'}):'未記録';

  function db(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
  async function get(){const d=await db();return new Promise((resolve,reject)=>{const r=d.transaction(STORE).objectStore(STORE).get(STATE);r.onsuccess=()=>{d.close();resolve(r.result||null)};r.onerror=()=>{d.close();reject(r.error)}})}
  async function put(v){const d=await db();return new Promise((resolve,reject)=>{const r=d.transaction(STORE,'readwrite').objectStore(STORE).put(v,STATE);r.onsuccess=()=>{d.close();resolve()};r.onerror=()=>{d.close();reject(r.error)}})}
  async function getMapsUsage(){const d=await db();return new Promise((resolve,reject)=>{const r=d.transaction(STORE).objectStore(STORE).get(MAP_USAGE_STATE);r.onsuccess=()=>{d.close();resolve(r.result||null)};r.onerror=()=>{d.close();reject(r.error)}})}
  async function putMapsUsage(value){const d=await db();return new Promise((resolve,reject)=>{const r=d.transaction(STORE,'readwrite').objectStore(STORE).put(value,MAP_USAGE_STATE);r.onsuccess=()=>{d.close();resolve()};r.onerror=()=>{d.close();reject(r.error)}})}
  async function save(){try{if(navigator.storage?.persist)await navigator.storage.persist().catch(()=>false);await put(shops);updateUI();return true}catch(e){console.error(e);alert('データを保存できませんでした。空き容量を確認し、バックアップを取ってからお試しください。');return false}}
  async function boot(){try{const saved=await get();if(Array.isArray(saved))shops=saved.filter(validShop);else{const old=JSON.parse(localStorage.getItem(LEGACY_KEY)||'[]');shops=Array.isArray(old)?old.filter(validShop):[];if(shops.length)await put(shops)}mapsUsage=normalizeMapsUsage(await getMapsUsage())}catch(e){console.error(e);mapsUsage=emptyMapsUsage();alert('保存データを読み込めませんでした。')}updateUI();updateMapsUsageNote()}

  function usageMonth(){const now=new Date();return `${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`}
  function emptyMapsUsage(){return {month:usageMonth(),mapLoads:0,searchRequests:0,placeSelections:0}}
  function normalizeMapsUsage(value){const base=emptyMapsUsage();if(!value||typeof value!=='object'||value.month!==base.month)return base;for(const key of ['mapLoads','searchRequests','placeSelections'])base[key]=Number.isFinite(Number(value[key]))?Math.max(0,Math.floor(Number(value[key]))):0;return base}
  function activeMapsUsage(){return normalizeMapsUsage(mapsUsage)}
  function usageLabel(type){return ({mapLoads:'地図表示',searchRequests:'店名検索',placeSelections:'店舗選択'})[type]||'Googleマップ'}
  function updateMapsUsageNote(){const note=$('#map-usage-note');if(!note)return;const usage=activeMapsUsage(),num=n=>n.toLocaleString('ja-JP');note.textContent=`無料枠の保護（${usage.month}）：地図 ${num(usage.mapLoads)} / ${num(MAPS_FREE_LIMIT)} ・ 検索 ${num(usage.searchRequests)} / ${num(MAPS_FREE_LIMIT)} ・ 店舗選択 ${num(usage.placeSelections)} / ${num(MAPS_FREE_LIMIT)}`}
  function setMapsUsageMessage(message=''){const el=$('#map-usage-message');if(el)el.textContent=message}
  async function prepareUsageMonth(){if(mapsUsage?.month===usageMonth())return;const reset=emptyMapsUsage();try{await putMapsUsage(reset);mapsUsage=reset;const mapBox=$('#leaflet-map');if(mapBox.classList.contains('map-quota-blocked')){mapBox.classList.remove('map-quota-blocked');mapBox.replaceChildren();$('#add-shop-btn').disabled=false;$('#locate-btn').disabled=false;const search=$('#place-search-input');if(search)search.disabled=true}updateMapsUsageNote();setMapsUsageMessage('')}catch(e){console.error(e);setMapsUsageMessage('利用回数を安全に保存できないため、Googleマップの利用を停止しました。')}}
  async function reserveMapsUsage(type){const usage=activeMapsUsage();if(usage[type]>=MAPS_FREE_LIMIT){setMapsUsageMessage(`今月の${usageLabel(type)}は無料上限（${MAPS_FREE_LIMIT.toLocaleString('ja-JP')}回）に達しました。来月に再開します。`);updateMapsUsageNote();return false}const next={...usage,[type]:usage[type]+1};try{await putMapsUsage(next);mapsUsage=next;updateMapsUsageNote();return true}catch(e){console.error(e);setMapsUsageMessage('利用回数を安全に保存できないため、Googleマップの利用を停止しました。');return false}}
  function mapQuotaReached(type){return activeMapsUsage()[type]>=MAPS_FREE_LIMIT}
  function lockMapForQuota(type='mapLoads'){placeSearchReady=false;clearTimeout(placeSearchTimer);const mapBox=$('#leaflet-map');mapBox.classList.add('map-quota-blocked');mapBox.replaceChildren();const notice=document.createElement('div');notice.className='map-quota-notice';notice.innerHTML=`<strong>今月の無料利用上限に達しました</strong><span>${esc(usageLabel(type))}は来月まで利用できません。</span>`;mapBox.append(notice);const search=$('#place-search-input');if(search)search.disabled=true;$('#place-search-results')?.replaceChildren();$('#add-shop-btn').disabled=true;$('#locate-btn').disabled=true;setMapsUsageMessage(`今月の${usageLabel(type)}は無料上限（${MAPS_FREE_LIMIT.toLocaleString('ja-JP')}回）に達しました。Google地図の表示を停止しています。`)}
  function setScreen(name,{centerCurrent=true}={}){$$('.screen').forEach(x=>x.classList.toggle('active',x.id===name));$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.nav===name));if(name==='map')setTimeout(async()=>{await initMap();if(map){google.maps.event.trigger(map,'resize');if(centerCurrent)centerOnCurrentPosition()}},50);updateUI();window.scrollTo({top:0,behavior:'smooth'})}
  function mapsKey(){return localStorage.getItem(MAPS_KEY)||''}
  function loadMaps(key){return new Promise((resolve,reject)=>{if(window.google?.maps)return resolve();const script=document.createElement('script');script.src=`https://maps.googleapis.com/maps/api/js?key=${encodeURIComponent(key)}&libraries=places&language=ja&region=JP&v=weekly`;script.async=true;script.onload=resolve;script.onerror=()=>reject(new Error('Googleマップを読み込めませんでした。APIキーの設定を確認してください。'));document.head.append(script)})}
  function setSelectedLocation(lat,lng){selectedPosition={lat:Number(lat),lng:Number(lng)};if(!map)return;if(selectionMarker)selectionMarker.setMap(null);selectionMarker=new google.maps.Marker({position:selectedPosition,map,icon:markerIcon('#2878c7'),title:'登録する位置'})}
  function centerOnCurrentPosition(showError=false){if(!map)return;if(!navigator.geolocation){if(showError)alert('このブラウザでは現在地を利用できません。');return}navigator.geolocation.getCurrentPosition(p=>{map.setCenter({lat:p.coords.latitude,lng:p.coords.longitude});map.setZoom(15)},()=>{if(showError)alert('現在地を取得できませんでした。位置情報の許可を確認してください。')},{enableHighAccuracy:false,timeout:10000,maximumAge:300000})}
  function clearPlaceResults(){const results=$('#place-search-results');if(results)results.replaceChildren()}
  function setupPlaceSearch(AutocompleteSuggestion,AutocompleteSessionToken){if(placeSearchReady)return;placeSearchReady=true;const input=$('#place-search-input'),results=$('#place-search-results');input.disabled=mapQuotaReached('searchRequests')||mapQuotaReached('placeSelections');if(input.disabled){setMapsUsageMessage('今月の店名検索または店舗選択は無料上限に達しました。来月に再開します。');return}let predictions=[];const closeResults=()=>{predictions=[];clearPlaceResults()};const renderResults=items=>{predictions=items;clearPlaceResults();items.forEach((prediction,index)=>{const item=document.createElement('li'),button=document.createElement('button'),text=prediction.text?.text||prediction.mainText?.text||'店舗候補';button.type='button';button.dataset.prediction=String(index);button.textContent=text;item.append(button);results.append(item)})};const search=async()=>{const query=input.value.trim(),sequence=++placeSearchSequence;if(query.length<2){closeResults();return}if(!await reserveMapsUsage('searchRequests')){input.disabled=true;closeResults();return}try{placeSearchToken||=new AutocompleteSessionToken();const response=await AutocompleteSuggestion.fetchAutocompleteSuggestions({input:query,includedRegionCodes:['jp'],sessionToken:placeSearchToken});if(sequence!==placeSearchSequence)return;renderResults((response.suggestions||[]).map(s=>s.placePrediction).filter(Boolean));if(!results.children.length)setMapsUsageMessage('該当するお店が見つかりませんでした。');else setMapsUsageMessage('')}catch(e){console.error(e);if(sequence===placeSearchSequence){closeResults();setMapsUsageMessage('店名検索を利用できませんでした。APIキーと Places API（New）の設定を確認してください。')}}};input.addEventListener('input',()=>{clearTimeout(placeSearchTimer);setMapsUsageMessage('');placeSearchTimer=setTimeout(search,320)});input.addEventListener('keydown',e=>{if(e.key==='Escape')closeResults()});results.addEventListener('click',async e=>{const button=e.target.closest('button[data-prediction]');if(!button||input.disabled)return;const prediction=predictions[Number(button.dataset.prediction)];if(!prediction)return;if(!await reserveMapsUsage('placeSelections')){input.disabled=true;closeResults();return}input.disabled=true;closeResults();placeSearchToken=null;try{const place=prediction.toPlace();await place.fetchFields({fields:['displayName','location']});if(!place.location){setMapsUsageMessage('この候補の位置を取得できませんでした。');return}const loc=place.location;setSelectedLocation(loc.lat(),loc.lng());map.setCenter(loc);map.setZoom(17);input.value='';openShopDialog(null,false,place.displayName||'')}catch(err){console.error(err);setMapsUsageMessage('お店の情報を取得できませんでした。もう一度お試しください。')}finally{input.disabled=mapQuotaReached('searchRequests')||mapQuotaReached('placeSelections')}})}
  async function initMap(){await bootPromise;await prepareUsageMonth();if(map)return true;if(mapInitPromise)return mapInitPromise;mapInitPromise=(async()=>{const key=mapsKey();if(!key){$('#map-settings-dialog').showModal();return false}if(!await reserveMapsUsage('mapLoads')){lockMapForQuota('mapLoads');return false}try{await loadMaps(key);map=new google.maps.Map($('#leaflet-map'),{center:{lat:34.7025,lng:135.4959},zoom:14,mapTypeControl:false,streetViewControl:false,fullscreenControl:false,clickableIcons:true,gestureHandling:'greedy'});map.addListener('click',e=>{setSelectedLocation(e.latLng.lat(),e.latLng.lng());openShopDialog()});const {AutocompleteSuggestion,AutocompleteSessionToken}=await google.maps.importLibrary('places');setupPlaceSearch(AutocompleteSuggestion,AutocompleteSessionToken);renderMarkers();return true}catch(e){console.error(e);setMapsUsageMessage(e.message||'Googleマップを読み込めませんでした。APIキーの設定を確認してください。');return false}})();try{return await mapInitPromise}finally{mapInitPromise=null}}
  const markerIcon=color=>({url:`data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="30" height="42" viewBox="0 0 30 42"><path fill="${color}" stroke="#fff" stroke-width="2" d="M15 1C7.3 1 1 7.3 1 15c0 10.5 14 26 14 26s14-15.5 14-26C29 7.3 22.7 1 15 1z"/><circle cx="15" cy="15" r="5" fill="#fff"/></svg>`)}`,scaledSize:new google.maps.Size(30,42),anchor:new google.maps.Point(15,42)});
  function renderMarkers(){if(!map||!window.google)return;markers.forEach(m=>m.setMap(null));markers=shops.map(s=>{const m=new google.maps.Marker({position:{lat:Number(s.lat),lng:Number(s.lng)},map,icon:markerIcon(s.status==='visited'?'#be2026':'#218c5b'),title:s.name});m.addListener('click',()=>showDetail(s.id));return m})}
  function focus(shop){setScreen('map',{centerCurrent:false});setTimeout(()=>{if(!map)return;map.setCenter({lat:Number(shop.lat),lng:Number(shop.lng)});map.setZoom(16);showDetail(shop.id)},300)}
  function seedInitialSlot(){if(spinning||!shops.length)return;const reels=$$('.slot-reel');if(!reels.length)return;let picks;if(shops.length>=3){const shuffled=[...shops];for(let i=shuffled.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[shuffled[i],shuffled[j]]=[shuffled[j],shuffled[i]]}picks=shuffled.slice(0,3)}else{const pick=shops[Math.floor(Math.random()*shops.length)];picks=[pick,pick,pick]}reels.forEach((reel,index)=>{reel.style.transition='none';reel.style.willChange='auto';reel.style.transform='translate3d(0,0,0)';reel.innerHTML=`<div class="reel-item">${esc(picks[index].name)}</div>`})}
  function updateUI(){const visited=shops.filter(s=>s.status==='visited'),unvisited=shops.filter(s=>s.status==='unvisited');$('#home-visited').textContent=visited.length;$('#home-unvisited').textContent=unvisited.length;$('#record-unvisited').textContent=unvisited.length;$('#record-year').textContent=visited.length;list('#visited-list',visited,'訪問済みのお店はまだありません');list('#unvisited-list',unvisited,'行きたいお店はまだありません');seedInitialSlot();renderMarkers()}
  function list(selector,items,empty){const el=$(selector);el.innerHTML=items.length?items.map(s=>`<button class="shop-row" data-shop="${s.id}">${s.photo?`<img src="${s.photo}" alt="">`:`<span class="row-dot ${s.status==='visited'?'red':'green'}"></span>`}<span><b>${esc(s.name)}</b><small>${s.status==='visited'?date(s.visitDate):'行きたいお店'}</small></span></button>`).join(''):`<p class="hint">${empty}</p>`;el.querySelectorAll('[data-shop]').forEach(b=>b.onclick=()=>showDetail(b.dataset.shop))}

  function openShopDialog(shop=null,convert=false,placeName=''){const f=$('#shop-form');f.reset();pendingPhoto=null;$('#form-error').textContent='';$('#photo-preview').classList.add('hidden');$('#shop-id').value=shop?.id||'';$('#shop-name').value=shop?.name||placeName;$('#shop-lat').value=shop?.lat??selectedPosition?.lat??'';$('#shop-lng').value=shop?.lng??selectedPosition?.lng??'';f.elements.status.value=convert?'visited':(shop?.status||'unvisited');$('#shop-date').value=shop?.visitDate||new Date().toISOString().slice(0,10);$('#shop-menu').value=shop?.menu||'';if(shop?.photo){$('#photo-preview').src=shop.photo;$('#photo-preview').classList.remove('hidden')}$('#form-title').textContent=convert?'訪問を記録':shop?'お店を編集':'お店を登録';$('#position-note').textContent=$('#shop-lat').value?`位置を設定済み：${Number($('#shop-lat').value).toFixed(5)}, ${Number($('#shop-lng').value).toFixed(5)}`:'地図をタップして位置を選択してください。';toggleVisit();$('#shop-dialog').showModal()}
  const toggleVisit=()=>$('#visit-fields').classList.toggle('hidden',$('#shop-form').elements.status.value!=='visited');

  function imageFrom(file){return new Promise((resolve,reject)=>{if(!file.type.startsWith('image/'))return reject(new Error('画像ファイルを選択してください。'));const url=URL.createObjectURL(file),img=new Image();img.onload=()=>resolve(img);img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('写真を読み込めませんでした。'))};img.src=url})}
  function clamp(){const box=$('#crop-viewport').clientWidth,w=crop.img.naturalWidth*crop.scale,h=crop.img.naturalHeight*crop.scale;crop.x=Math.min(0,Math.max(box-w,crop.x));crop.y=Math.min(0,Math.max(box-h,crop.y))}
  function paintCrop(){const i=$('#crop-image');i.style.width=`${crop.img.naturalWidth*crop.scale}px`;i.style.height=`${crop.img.naturalHeight*crop.scale}px`;i.style.transform=`translate(${crop.x}px,${crop.y}px)`}
  async function beginCrop(file){const img=await imageFrom(file),box=320,min=Math.max(box/img.naturalWidth,box/img.naturalHeight);crop={img,min,scale:min,x:(box-img.naturalWidth*min)/2,y:(box-img.naturalHeight*min)/2};cropPointers.clear();cropGesture=null;$('#crop-image').src=img.src;paintCrop();$('#crop-dialog').showModal()}
  const bytes=data=>Math.ceil((data.length-data.indexOf(',')-1)*3/4);
  function compress(square){for(let side=800;;side=Math.round(side*.8)){const c=document.createElement('canvas');c.width=c.height=side;c.getContext('2d').drawImage(square,0,0,side,side);for(const q of [.78,.68,.58,.48,.38,.3]){const data=c.toDataURL('image/jpeg',q);if(bytes(data)<=MAX_PHOTO||side<=280)return data}}}
  function applyCrop(){if(!crop)return;const box=$('#crop-viewport').clientWidth,c=document.createElement('canvas');c.width=c.height=800;const sx=-crop.x/crop.scale,sy=-crop.y/crop.scale,side=box/crop.scale;c.getContext('2d').drawImage(crop.img,sx,sy,side,side,0,0,800,800);pendingPhoto=compress(c);URL.revokeObjectURL(crop.img.src);$('#photo-preview').src=pendingPhoto;$('#photo-preview').classList.remove('hidden');$('#crop-dialog').close();$('#shop-photo').value='';crop=null}
  const cropDistance=([a,b])=>Math.hypot(a.x-b.x,a.y-b.y),cropCenter=([a,b])=>({x:(a.x+b.x)/2,y:(a.y+b.y)/2});
  function startCropGesture(){const points=[...cropPointers.values()];if(points.length>=2){const center=cropCenter(points),scale=crop.scale;cropGesture={type:'pinch',distance:cropDistance(points),center,scale,x:crop.x,y:crop.y,imageX:(center.x-crop.x)/scale,imageY:(center.y-crop.y)/scale}}else if(points.length===1)cropGesture={type:'drag',point:points[0],x:crop.x,y:crop.y}}
  const cropViewport=$('#crop-viewport');cropViewport.addEventListener('pointerdown',e=>{if(!crop)return;cropViewport.setPointerCapture(e.pointerId);cropPointers.set(e.pointerId,{x:e.clientX,y:e.clientY});startCropGesture()});cropViewport.addEventListener('pointermove',e=>{if(!crop||!cropPointers.has(e.pointerId)||!cropGesture)return;cropPointers.set(e.pointerId,{x:e.clientX,y:e.clientY});const points=[...cropPointers.values()];if(cropGesture.type==='pinch'&&points.length>=2){const center=cropCenter(points),ratio=cropDistance(points)/cropGesture.distance;crop.scale=Math.min(crop.min*4,Math.max(crop.min,cropGesture.scale*ratio));crop.x=center.x-cropGesture.imageX*crop.scale;crop.y=center.y-cropGesture.imageY*crop.scale}else if(cropGesture.type==='drag'&&points.length===1){const point=points[0];crop.x=cropGesture.x+point.x-cropGesture.point.x;crop.y=cropGesture.y+point.y-cropGesture.point.y}else{startCropGesture();return}clamp();paintCrop()});function endCropPointer(e){cropPointers.delete(e.pointerId);if(cropPointers.size)startCropGesture();else cropGesture=null}cropViewport.addEventListener('pointerup',endCropPointer);cropViewport.addEventListener('pointercancel',endCropPointer);
  $('#crop-apply').onclick=applyCrop;$('#crop-cancel').onclick=()=>{if(crop)URL.revokeObjectURL(crop.img.src);$('#crop-dialog').close();crop=null;$('#shop-photo').value=''};$('#shop-photo').onchange=async e=>{if(!e.target.files[0])return;try{await beginCrop(e.target.files[0])}catch(err){$('#form-error').textContent=err.message}};
  $('#shop-form').addEventListener('submit',async e=>{e.preventDefault();const error=$('#form-error'),name=$('#shop-name').value.trim(),lat=Number($('#shop-lat').value),lng=Number($('#shop-lng').value),status=e.currentTarget.elements.status.value;error.textContent='';if(!name){error.textContent='店名を入力してください。';return}if(!Number.isFinite(lat)||!Number.isFinite(lng)){error.textContent='地図をタップして店舗位置を指定してください。';return}const old=shops.find(s=>s.id===$('#shop-id').value),shop={id:old?.id||uid(),name,lat,lng,status,photo:pendingPhoto||old?.photo||null,visitDate:status==='visited'?$('#shop-date').value:'',menu:status==='visited'?$('#shop-menu').value.trim():''};shops=old?shops.map(s=>s.id===shop.id?shop:s):[...shops,shop];if(await save()){$('#shop-dialog').close();selectedPosition=null;if(selectionMarker){selectionMarker.setMap(null);selectionMarker=null}pendingPhoto=null}});

  function showDetail(shopId){const s=shops.find(x=>x.id===shopId);if(!s)return;detailShopId=s.id;$('#detail-name').textContent=s.name;const p=$('#detail-photo');p.classList.toggle('hidden',!s.photo);if(s.photo)p.src=s.photo;$('#detail-content').innerHTML=s.status==='visited'?`<p class="detail-line">訪問日：${date(s.visitDate)}</p><p class="detail-line">食べたメニュー：${esc(s.menu||'未記録')}</p>`:`<p class="detail-line"><span class="dot green"></span>行きたいお店</p>`;$('#convert-btn').classList.toggle('hidden',s.status==='visited');$('#detail-dialog').showModal()}
  $('#edit-btn').onclick=()=>{const s=shops.find(x=>x.id===detailShopId);$('#detail-dialog').close();openShopDialog(s)};$('#convert-btn').onclick=()=>{const s=shops.find(x=>x.id===detailShopId);$('#detail-dialog').close();openShopDialog(s,true)};$('#delete-btn').onclick=async()=>{const s=shops.find(x=>x.id===detailShopId);if(s&&confirm(`「${s.name}」を削除しますか？`)){shops=shops.filter(x=>x.id!==s.id);await save();$('#detail-dialog').close()}};
  const target=()=>selectedFilter==='all'?shops:shops.filter(s=>s.status===selectedFilter);
  $$('.filter').forEach(b=>b.onclick=()=>{$$('.filter').forEach(x=>x.classList.toggle('active',x===b));selectedFilter=b.dataset.filter;$('#gacha-message').textContent='';$('#result-map-btn').classList.add('hidden')});
  let audioContext=null;function audio(){const ctx=audioContext||(audioContext=new(window.AudioContext||window.webkitAudioContext)());ctx.resume?.();return ctx}function tone(freq,duration=.08,type='sine',volume=.05,when=0){try{const ctx=audio(),osc=ctx.createOscillator(),gain=ctx.createGain();osc.type=type;osc.frequency.setValueAtTime(freq,ctx.currentTime+when);gain.gain.setValueAtTime(volume,ctx.currentTime+when);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+when+duration);osc.connect(gain).connect(ctx.destination);osc.start(ctx.currentTime+when);osc.stop(ctx.currentTime+when+duration)}catch{}}function clickSound(){tone(680,.06,'triangle',.045)}function startSpinSound(){try{const ctx=audio(),osc=ctx.createOscillator(),filter=ctx.createBiquadFilter(),gain=ctx.createGain(),now=ctx.currentTime;osc.type='sawtooth';osc.frequency.setValueAtTime(82,now);osc.frequency.exponentialRampToValueAtTime(155,now+1.1);osc.frequency.exponentialRampToValueAtTime(66,now+3.6);filter.type='lowpass';filter.frequency.value=620;gain.gain.setValueAtTime(.001,now);gain.gain.linearRampToValueAtTime(.028,now+.18);osc.connect(filter).connect(gain).connect(ctx.destination);osc.start();return()=>{gain.gain.cancelScheduledValues(ctx.currentTime);gain.gain.setValueAtTime(.028,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.12);osc.stop(ctx.currentTime+.14)}}catch{return()=>{}}}function winSound(){[0,.12,.24,.39,.55].forEach((when,i)=>tone([392,523,659,784,1046][i],.34,'triangle',.085,when));try{const ctx=audio(),buffer=ctx.createBuffer(1,ctx.sampleRate*.46,ctx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*(1-i/data.length);const noise=ctx.createBufferSource(),filter=ctx.createBiquadFilter(),gain=ctx.createGain();filter.type='highpass';filter.frequency.value=1200;gain.gain.setValueAtTime(.12,ctx.currentTime+.04);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.46);noise.buffer=buffer;noise.connect(filter).connect(gain).connect(ctx.destination);noise.start(ctx.currentTime+.04)}catch{}}function celebrate(){const box=$('#confetti'),colors=['#ffca3a','#ff595e','#4cc9f0','#80ed99','#c77dff'];box.replaceChildren();for(let i=0;i<54;i++){const piece=document.createElement('i');piece.style.left=`${8+Math.random()*84}%`;piece.style.background=colors[i%colors.length];piece.style.setProperty('--x',`${(Math.random()-.5)*260}px`);piece.style.setProperty('--r',`${Math.random()*900-450}deg`);piece.style.animationDelay=`${Math.random()*.16}s`;box.append(piece)}setTimeout(()=>box.replaceChildren(),1800)}
  $('#spin-btn').onclick=()=>{const pool=target();if(spinning)return;if(!pool.length){$('#gacha-message').textContent=`${selectedFilter==='visited'?'訪問済み店舗':selectedFilter==='unvisited'?'未訪問店舗':'店舗'}が登録されていません。`;return}spinning=true;clickSound();const stopSpinSound=startSpinSound(),result=$('#slot-result'),durations=[5000,6000,7000];$('#spin-btn').disabled=true;$('#gacha-message').textContent='SPINNING…';$('#result-map-btn').classList.add('hidden');result.classList.add('hidden');result.classList.remove('with-photo');$('#slot-stage').classList.add('is-spinning');const winner=pool[Math.floor(Math.random()*pool.length)],height=92;$$('.slot-reel').forEach((reel,index)=>{const items=[winner,...Array.from({length:27+index*4},()=>pool[Math.floor(Math.random()*pool.length)])],start=-(items.length-1)*height;reel.style.transition='none';reel.style.willChange='transform';reel.style.transform=`translate3d(0,${start}px,0)`;reel.innerHTML=items.map(s=>`<div class="reel-item">${esc(s.name)}</div>`).join('');void reel.offsetHeight;requestAnimationFrame(()=>{reel.style.transitionProperty='transform';reel.style.transitionDuration=`${durations[index]}ms`;reel.style.transitionTimingFunction='cubic-bezier(.16,.66,.28,1)';reel.style.transform='translate3d(0,0,0)'})});durations.forEach((duration,index)=>setTimeout(()=>{reelStopSound();if(index===2){stopSpinSound();setTimeout(()=>{celebrationSound();celebrate()},500)}},duration));setTimeout(()=>{spinning=false;stopSpinSound();lastResult=winner;$('#spin-btn').disabled=false;$('#slot-stage').classList.remove('is-spinning');$$('.slot-reel').forEach(reel=>reel.style.willChange='auto');$('#slot-name').textContent=winner.name;$('#slot-status').textContent=winner.status==='visited'?'VISITED • 訪問済み':'WISHLIST • 行きたいお店';const photo=$('#slot-photo'),hasPhoto=Boolean(winner.photo);photo.classList.toggle('hidden',!hasPhoto);if(hasPhoto)photo.src=winner.photo;result.classList.toggle('with-photo',hasPhoto);result.classList.remove('hidden');$('#result-map-btn').classList.remove('hidden');$('#gacha-message').textContent='JACKPOT — 今日の一杯、決定！'},7500)};
  $('#result-map-btn').onclick=()=>lastResult&&focus(lastResult);$('#add-shop-btn').onclick=()=>openShopDialog();$('#locate-btn').onclick=()=>centerOnCurrentPosition(true);$('#map-settings-btn').onclick=()=>{$('#maps-api-key').value=mapsKey();$('#map-settings-error').textContent='';$('#map-settings-dialog').showModal()};$('#map-settings-form').onsubmit=e=>{e.preventDefault();const key=$('#maps-api-key').value.trim();if(!key){$('#map-settings-error').textContent='APIキーを入力してください。';return}localStorage.setItem(MAPS_KEY,key);location.reload()};$$('[data-nav]').forEach(b=>b.onclick=()=>setScreen(b.dataset.nav));$$('[data-close]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.close).close());$$('#shop-form input[name=status]').forEach(r=>r.onchange=toggleVisit);
  $('#export-btn').onclick=()=>{const blob=new Blob([JSON.stringify({version:2,exportedAt:new Date().toISOString(),shops,mapsUsage:activeMapsUsage()},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`ramen-gacha-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
  $('#import-input').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onerror=()=>alert('ファイルを読み込めませんでした。');r.onload=async()=>{try{const data=JSON.parse(r.result);if(!data||![1,2].includes(data.version)||!Array.isArray(data.shops)||!data.shops.every(validShop))throw Error();if(!confirm('現在のデータを置き換えてインポートします。よろしいですか？'))return;shops=data.shops;if(data.mapsUsage){mapsUsage=normalizeMapsUsage(data.mapsUsage);await putMapsUsage(mapsUsage);updateMapsUsageNote()}if(await save())alert(`${shops.length}件の店舗データを復元しました。`)}catch{alert('不正なJSONファイルです。RAMEN SLOTからエクスポートしたファイルを選択してください。')}finally{e.target.value=''}};r.readAsText(f)};
  function burst(when=0,duration=.16,volume=.06,cutoff=1200){try{const ctx=audio(),length=Math.max(1,Math.floor(ctx.sampleRate*duration)),buffer=ctx.createBuffer(1,length,ctx.sampleRate),data=buffer.getChannelData(0),source=ctx.createBufferSource(),filter=ctx.createBiquadFilter(),gain=ctx.createGain(),now=ctx.currentTime+when;for(let i=0;i<length;i++)data[i]=(Math.random()*2-1)*(1-i/length);filter.type='bandpass';filter.frequency.value=cutoff;filter.Q.value=.7;gain.gain.setValueAtTime(.001,now);gain.gain.exponentialRampToValueAtTime(volume,now+.012);gain.gain.exponentialRampToValueAtTime(.001,now+duration);source.buffer=buffer;source.connect(filter).connect(gain).connect(ctx.destination);source.start(now)}catch{}}
  function drumHit(power=.07){try{const ctx=audio(),osc=ctx.createOscillator(),gain=ctx.createGain(),now=ctx.currentTime;osc.type='sine';osc.frequency.setValueAtTime(168,now);osc.frequency.exponentialRampToValueAtTime(49,now+.13);gain.gain.setValueAtTime(power,now);gain.gain.exponentialRampToValueAtTime(.001,now+.15);osc.connect(gain).connect(ctx.destination);osc.start(now);osc.stop(now+.16)}catch{}burst(0,.075,power*.62,2100)}
  const slotSlowdownClip=new Audio('sounds/roulette-slowdown.mp3'),slotStopClip=new Audio('sounds/roulette-stop-button.mp3'),partyPopperClip=new Audio('sounds/party-popper.mp3'),streamerClip=new Audio('sounds/confetti-streamers.mp3');slotSlowdownClip.preload='auto';slotStopClip.preload='auto';partyPopperClip.preload='auto';streamerClip.preload='auto';let rouletteSpinBuffer=null,rouletteSpinPromise=null;
  function loadRouletteSpinBuffer(){if(rouletteSpinBuffer)return Promise.resolve(rouletteSpinBuffer);if(!rouletteSpinPromise){rouletteSpinPromise=fetch('sounds/roulette-spinning.mp3').then(response=>response.arrayBuffer()).then(data=>audio().decodeAudioData(data)).then(buffer=>(rouletteSpinBuffer=buffer)).catch(()=>null)}return rouletteSpinPromise}loadRouletteSpinBuffer();
  function reelStopSound(){const stop=slotStopClip.cloneNode();stop.volume=.72;stop.playbackRate=1;stop.play().catch(()=>{})}
  function celebrationSound(){const launch=(clip,delay,volume,rate)=>setTimeout(()=>{const sound=clip.cloneNode();sound.volume=volume;sound.playbackRate=rate;sound.play().catch(()=>{})},delay);[[0,.5,.92],[65,.39,1.04],[135,.33,.86],[215,.26,1.12]].forEach(([delay,volume,rate])=>launch(partyPopperClip,delay,volume,rate));[[800,.34,.9],[870,.29,1.02],[940,.25,1.1],[1015,.21,.96],[1090,.18,1.15]].forEach(([delay,volume,rate])=>launch(streamerClip,delay,volume,rate))}
  startSpinSound=()=>{let stopped=false,rotationActive=true,source=null,gain=null,slowdown=null;const stopRotation=()=>{if(!source||!gain)return;const ctx=audio(),now=ctx.currentTime;gain.gain.cancelScheduledValues(now);gain.gain.setValueAtTime(Math.max(.001,gain.gain.value),now);gain.gain.exponentialRampToValueAtTime(.001,now+.12);source.stop(now+.14);source=null};loadRouletteSpinBuffer().then(buffer=>{if(stopped||!rotationActive||!buffer)return;const ctx=audio();source=ctx.createBufferSource();gain=ctx.createGain();source.buffer=buffer;source.loop=true;source.loopStart=.015;source.loopEnd=Math.max(.02,buffer.duration-.02);gain.gain.value=.54;source.connect(gain).connect(ctx.destination);source.start()});const changeover=setTimeout(()=>{if(stopped)return;rotationActive=false;slowdown=slotSlowdownClip.cloneNode();slowdown.volume=.54;slowdown.playbackRate=1;slowdown.play().catch(()=>{});stopRotation()},4000);return()=>{if(stopped)return;stopped=true;rotationActive=false;clearTimeout(changeover);stopRotation();if(slowdown){slowdown.pause();slowdown.currentTime=0}}};
  winSound=()=>{[0,.09,.18,.3,.43,.57].forEach((when,i)=>{tone([392,523,659,784,1046,1318][i],.48,'triangle',.09,when);tone([784,1046,1318,1568,2093,2637][i],.2,'sine',.026,when+.012)});burst(.02,.38,.13,2800);burst(.23,.34,.105,3800);burst(.49,.3,.08,4700)};
  celebrate=()=>{const box=$('#confetti'),colors=['#f6c84c','#e94a52','#4a9be6','#37a770','#f29432','#f7f0da'];box.replaceChildren();for(let i=0;i<210;i++){const left=i%2===0,piece=document.createElement('i'),wide=5+Math.random()*7,tall=9+Math.random()*13;piece.className=left?'cannon-left':'cannon-right';piece.style.left=left?`${-3+Math.random()*8}vw`:`${95-Math.random()*5}vw`;piece.style.top=`${76+Math.random()*17}vh`;piece.style.background=colors[Math.floor(Math.random()*colors.length)];piece.style.setProperty('--launch-x',`${left?42+Math.random()*25:-(42+Math.random()*25)}vw`);piece.style.setProperty('--peak-y',`${-(48+Math.random()*22)}vh`);piece.style.setProperty('--fall-x',`${left?28+Math.random()*72:-(28+Math.random()*72)}vw`);piece.style.setProperty('--fall-y',`${25+Math.random()*34}vh`);piece.style.setProperty('--launch-r',`${(Math.random()-.5)*720}deg`);piece.style.setProperty('--r',`${(Math.random()-.5)*1800}deg`);piece.style.setProperty('--d',`${3.1+Math.random()*1.8}s`);piece.style.setProperty('--delay',`${Math.random()*.32}s`);piece.style.setProperty('--w',`${wide}px`);piece.style.setProperty('--h',`${tall}px`);piece.style.borderRadius=Math.random()>.88?'50%':'1px';box.append(piece)}setTimeout(()=>box.replaceChildren(),5400)};
  celebrate=()=>{const box=$('#confetti'),colors=['#f6c84c','#ec4d58','#5aa9ed','#49b97c','#f39a38','#f7f0da'];box.replaceChildren();for(let i=0;i<240;i++){const left=i%2===0,piece=document.createElement('i'),wide=5+Math.random()*8,tall=10+Math.random()*15,start=left?-4+Math.random()*7:97-Math.random()*6,target=-5+Math.random()*110;piece.className=left?'cannon-left':'cannon-right';piece.style.left=`${start}vw`;piece.style.top=`${77+Math.random()*16}vh`;piece.style.setProperty('--paper',colors[Math.floor(Math.random()*colors.length)]);piece.style.setProperty('--launch-x',`${left?44+Math.random()*23:-(44+Math.random()*23)}vw`);piece.style.setProperty('--peak-y',`${-(51+Math.random()*21)}vh`);piece.style.setProperty('--fall-x',`${target-start}vw`);piece.style.setProperty('--fall-y',`${28+Math.random()*39}vh`);piece.style.setProperty('--launch-r',`${(Math.random()-.5)*900}deg`);piece.style.setProperty('--r',`${(Math.random()-.5)*2160}deg`);piece.style.setProperty('--d',`${5.6+Math.random()*2.2}s`);piece.style.setProperty('--delay',`${Math.random()*.42}s`);piece.style.setProperty('--w',`${wide}px`);piece.style.setProperty('--h',`${tall}px`);piece.style.borderRadius=Math.random()>.91?'50%':'1px';box.append(piece)}setTimeout(()=>box.replaceChildren(),8700)};
  celebrate=()=>{const box=$('#confetti'),metals=['#ffd85a','#f7f0bd','#c9d1db','#f8fafc','#c69432','#aeb7c4'];box.replaceChildren();for(let i=0;i<280;i++){const left=i%2===0,piece=document.createElement('i'),wide=4+Math.random()*8,tall=11+Math.random()*17,start=left?-5+Math.random()*8:97-Math.random()*5,launch=left?6+Math.random()*105:-(6+Math.random()*105),peak=-(48+Math.random()*25),target=-6+Math.random()*112,fall=target-start,fallY=30+Math.random()*42,midX=(launch+fall)/2,midY=(peak+fallY)/2;piece.className=left?'cannon-fan-left':'cannon-fan-right';piece.style.left=`${start}vw`;piece.style.top=`${75+Math.random()*18}vh`;piece.style.setProperty('--paper',metals[Math.floor(Math.random()*metals.length)]);piece.style.setProperty('--launch-x',`${launch}vw`);piece.style.setProperty('--peak-y',`${peak}vh`);piece.style.setProperty('--mid-x',`${midX}vw`);piece.style.setProperty('--mid-y',`${midY}vh`);piece.style.setProperty('--fall-x',`${fall}vw`);piece.style.setProperty('--fall-y',`${fallY}vh`);piece.style.setProperty('--sway',`${-7+Math.random()*14}vw`);piece.style.setProperty('--launch-r',`${(Math.random()-.5)*1080}deg`);piece.style.setProperty('--r',`${(Math.random()-.5)*2520}deg`);piece.style.setProperty('--d',`${6.4+Math.random()*2.8}s`);piece.style.setProperty('--delay',`${Math.random()*.48}s`);piece.style.setProperty('--w',`${wide}px`);piece.style.setProperty('--h',`${tall}px`);piece.style.borderRadius=Math.random()>.93?'50%':'1px';box.append(piece)}setTimeout(()=>box.replaceChildren(),10200)};
  celebrate=()=>{const box=$('#confetti'),metals=['#ffd85a','#f7f0bd','#c9d1db','#f8fafc','#c69432','#aeb7c4'],particles=[],width=innerWidth,height=innerHeight;box.replaceChildren();for(let i=0;i<220;i++){const left=i%2===0,el=document.createElement('i'),x=left?-16:width+16,y=height*(.78+Math.random()*.15),wide=4+Math.random()*8,tall=10+Math.random()*17;el.className='physics-confetti';el.style.setProperty('--paper',metals[Math.floor(Math.random()*metals.length)]);el.style.setProperty('--w',`${wide}px`);el.style.setProperty('--h',`${tall}px`);el.style.borderRadius=Math.random()>.93?'50%':'1px';box.append(el);particles.push({el,x,y,vx:(left?1:-1)*(165+Math.random()*245),vy:-(420+Math.random()*145),spin:(Math.random()-.5)*900,rotation:Math.random()*360,phase:Math.random()*Math.PI*2})}let last=performance.now,start=last;const frame=now=>{const dt=Math.min(.032,(now-last)/1000);last=now;for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.vy+=235*dt;p.vx+=Math.sin(now*.0022+p.phase)*20*dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.rotation+=p.spin*dt;const sway=Math.sin(now*.003+p.phase)*4,fade=p.vy>0&&p.y>height*.67?Math.max(0,1-(p.y-height*.67)/(height*.42)):1;p.el.style.opacity=fade;p.el.style.transform=`translate3d(${p.x+sway}px,${p.y}px,0) rotate(${p.rotation}deg)`;if(p.y>height*1.15||fade<=0)particles.splice(i,1)}if(particles.length&&now-start<11000)requestAnimationFrame(frame);else box.replaceChildren()};requestAnimationFrame(frame)};
  celebrate=()=>{const box=$('#confetti'),metals=['#ffd85a','#f7f0bd','#c9d1db','#f8fafc','#c69432','#aeb7c4'];if(box.parentElement!==document.body)document.body.append(box);box.replaceChildren();box.style.display='block';box.style.visibility='visible';for(let i=0;i<250;i++){const left=i%2===0,piece=document.createElement('i'),startX=left?-5+Math.random()*9:96-Math.random()*7,startY=78+Math.random()*15,peakX=left?20+Math.random()*75:-(20+Math.random()*75),peakY=-(46+Math.random()*36),endX=left?28+Math.random()*74:-(28+Math.random()*74),endY=58+Math.random()*32,fall1X=peakX+(endX-peakX)*.125+(Math.random()-.5)*(22+Math.random()*12),fall2X=peakX+(endX-peakX)*.25+(Math.random()-.5)*(28+Math.random()*14),fall3X=peakX+(endX-peakX)*.375+(Math.random()-.5)*(24+Math.random()*16),fall4X=peakX+(endX-peakX)*.5+(Math.random()-.5)*(32+Math.random()*18),fall5X=peakX+(endX-peakX)*.625+(Math.random()-.5)*(24+Math.random()*16),fall6X=peakX+(endX-peakX)*.75+(Math.random()-.5)*(28+Math.random()*14),fall7X=peakX+(endX-peakX)*.875+(Math.random()-.5)*(22+Math.random()*12),fall1Y=peakY+(endY-peakY)*.125,fall2Y=peakY+(endY-peakY)*.25,fall3Y=peakY+(endY-peakY)*.375,fall4Y=peakY+(endY-peakY)*.5,fall5Y=peakY+(endY-peakY)*.625,fall6Y=peakY+(endY-peakY)*.75,fall7Y=peakY+(endY-peakY)*.875,fallXs=[fall1X,fall2X,fall3X,fall4X,fall5X,fall6X,fall7X],fallYs=[fall1Y,fall2Y,fall3Y,fall4Y,fall5Y,fall6Y,fall7Y];piece.className='physics-confetti';piece.style.left=`${startX}vw`;piece.style.top=`${startY}vh`;piece.style.setProperty('--paper',metals[Math.floor(Math.random()*metals.length)]);piece.style.setProperty('--w',`${4+Math.random()*8}px`);piece.style.setProperty('--h',`${10+Math.random()*17}px`);piece.style.setProperty('--peak-x',`${peakX}vw`);piece.style.setProperty('--peak-y',`${peakY}vh`);fallXs.forEach((value,n)=>{piece.style.setProperty(`--fall${n+1}-x`,`${value}vw`);piece.style.setProperty(`--fall${n+1}-y`,`${fallYs[n]}vh`)});piece.style.setProperty('--end-x',`${endX}vw`);piece.style.setProperty('--end-y',`${endY}vh`);piece.style.setProperty('--turn-a',`${(Math.random()-.5)*720}deg`);piece.style.setProperty('--turn-b',`${(Math.random()-.5)*1500}deg`);piece.style.setProperty('--turn-c',`${(Math.random()-.5)*2300}deg`);piece.style.setProperty('--d',`${6.8+Math.random()*2.8}s`);piece.style.setProperty('--delay','0s');piece.style.borderRadius=Math.random()>.93?'50%':'1px';box.append(piece)}setTimeout(()=>box.replaceChildren(),10200)};
  let doorRevealBuffer=null,doorRevealPromise=null,stopDoorRevealSound=()=>{};
  function loadDoorRevealSound(){if(doorRevealBuffer)return Promise.resolve(doorRevealBuffer);if(!doorRevealPromise){doorRevealPromise=fetch('sounds/jackpot-door-reveal.mp3').then(response=>response.arrayBuffer()).then(data=>audio().decodeAudioData(data)).then(buffer=>(doorRevealBuffer=buffer)).catch(()=>null)}return doorRevealPromise}
  loadDoorRevealSound();
  function jackpotSound(){stopDoorRevealSound();let stopped=false,sources=[];const stop=()=>{if(stopped)return;stopped=true;const now=audio().currentTime;sources.forEach(({source,gain})=>{try{gain.gain.cancelScheduledValues(now);gain.gain.setValueAtTime(Math.max(.0001,gain.gain.value),now);gain.gain.exponentialRampToValueAtTime(.0001,now+.18);source.stop(now+.21)}catch{}})};stopDoorRevealSound=stop;loadDoorRevealSound().then(buffer=>{if(stopped||!buffer)return;const ctx=audio(),start=ctx.currentTime+.015,play=(at,offset,length,rate,volume,fade=.12)=>{const source=ctx.createBufferSource(),gain=ctx.createGain(),from=start+at,to=from+length;source.buffer=buffer;source.playbackRate.value=rate;gain.gain.setValueAtTime(.0001,from);gain.gain.linearRampToValueAtTime(volume,from+.025);gain.gain.setValueAtTime(volume,Math.max(from+.035,to-fade));gain.gain.exponentialRampToValueAtTime(.0001,to);source.connect(gain).connect(ctx.destination);source.start(from,offset);source.stop(to+.015);sources.push({source,gain})};play(0,.02,.55,1.08,.62,.09);play(.48,.61,2.67,.94,.76,1.12)});return stop}
  let frameWhineBuffer=null,frameWhinePromise=null,stopFrameWhine=()=>{};
  function loadFrameWhine(){if(frameWhineBuffer)return Promise.resolve(frameWhineBuffer);if(!frameWhinePromise){frameWhinePromise=fetch('sounds/jackpot-frame-whine.mp3').then(response=>response.arrayBuffer()).then(data=>audio().decodeAudioData(data)).then(buffer=>(frameWhineBuffer=buffer)).catch(()=>null)}return frameWhinePromise}
  function startFrameWhine(){stopFrameWhine();let stopped=false;const sources=[];const stop=()=>{if(stopped)return;stopped=true;const now=audio().currentTime;sources.forEach(({source,gain})=>{try{gain.gain.cancelScheduledValues(now);gain.gain.setValueAtTime(Math.max(.001,gain.gain.value),now);gain.gain.exponentialRampToValueAtTime(.001,now+.06);source.stop(now+.075)}catch{}})};stopFrameWhine=stop;loadFrameWhine().then(buffer=>{if(stopped||!buffer)return;const ctx=audio(),start=ctx.currentTime+.015,finish=start+2.02,raw=Math.max(.08,buffer.duration-.02),shortLength=Math.max(.14,Math.min(.27,raw*.53)),overlap=.029;let at=start;const play=(when,end)=>{const source=ctx.createBufferSource(),gain=ctx.createGain();source.buffer=buffer;source.playbackRate.value=1;gain.gain.setValueAtTime(.001,when);gain.gain.linearRampToValueAtTime(.66,when+.014);gain.gain.setValueAtTime(.66,Math.max(when+.02,end-.05));gain.gain.linearRampToValueAtTime(.001,end);source.connect(gain).connect(ctx.destination);source.start(when,.01);source.stop(end+.01);sources.push({source,gain})};for(let i=0;i<3;i++){play(at,Math.min(at+shortLength,finish));at+=shortLength-overlap}play(at,Math.min(at+raw,finish))});return stop}
  loadFrameWhine();
  let jackpotReelStops=0,jackpotSequence=0;const baseReelStopSound=reelStopSound;
  reelStopSound=()=>{baseReelStopSound();jackpotReelStops++;if(jackpotReelStops!==3)return;const sequence=++jackpotSequence,stage=$('#slot-stage'),spinButton=$('#spin-btn');stage.classList.add('is-jackpot-prelude');startFrameWhine();$('#result-map-btn').classList.add('hidden');setTimeout(()=>{if(sequence!==jackpotSequence)return;spinning=true;spinButton.disabled=true;$('#result-map-btn').classList.add('hidden')},505);setTimeout(()=>{if(sequence!==jackpotSequence)return;stopFrameWhine();stage.classList.remove('is-jackpot-prelude');stage.classList.add('is-jackpot');jackpotSound()},2000);setTimeout(()=>{if(sequence!==jackpotSequence)return;spinning=false;spinButton.disabled=false;$('#result-map-btn').classList.remove('hidden')},4250)};
  clickSound=()=>{jackpotSequence++;jackpotReelStops=0;stopFrameWhine();stopDoorRevealSound();$('#slot-stage').classList.remove('is-jackpot','is-jackpot-prelude');$('#confetti').replaceChildren();tone(680,.06,'triangle',.045)};
  celebrationSound=()=>{};
  celebrate=()=>{};
  $('#slot-result').insertAdjacentHTML('afterbegin','<div class="jackpot-spotlights" aria-hidden="true"><i class="spot-tl"></i><i class="spot-tr"></i><i class="spot-bl"></i><i class="spot-br"></i></div>');$('.slot-machine').insertAdjacentHTML('beforeend','<div class="side-lamps" aria-hidden="true"><i class="l1"></i><i class="l2"></i><i class="l3"></i><i class="r1"></i><i class="r2"></i><i class="r3"></i></div>');

  // 音源は Web Audio で鳴らし、停止音と回転→減速のつなぎを端末差なく安定させる。
  let reelStopBuffer=null,reelStopPromise=null,slowdownBuffer=null,slowdownPromise=null;
  function loadReelStopBuffer(){if(reelStopBuffer)return Promise.resolve(reelStopBuffer);if(!reelStopPromise)reelStopPromise=fetch('sounds/roulette-stop-button.mp3').then(r=>r.arrayBuffer()).then(data=>audio().decodeAudioData(data)).then(buffer=>(reelStopBuffer=buffer)).catch(()=>null);return reelStopPromise}
  function loadSlowdownBuffer(){if(slowdownBuffer)return Promise.resolve(slowdownBuffer);if(!slowdownPromise)slowdownPromise=fetch('sounds/roulette-slowdown.mp3').then(r=>r.arrayBuffer()).then(data=>audio().decodeAudioData(data)).then(buffer=>(slowdownBuffer=buffer)).catch(()=>null);return slowdownPromise}
  function playReelStopSound(){
    if(!reelStopBuffer){const fallback=slotStopClip.cloneNode();fallback.currentTime=0;fallback.volume=.9;fallback.play().catch(()=>{});loadReelStopBuffer();return}
    try{const ctx=audio(),source=ctx.createBufferSource(),gain=ctx.createGain(),now=ctx.currentTime;source.buffer=reelStopBuffer;gain.gain.setValueAtTime(.9,now);gain.gain.exponentialRampToValueAtTime(.001,now+Math.max(.12,reelStopBuffer.duration));source.connect(gain).connect(ctx.destination);source.start(now)}catch{}
  }
  loadReelStopBuffer();loadSlowdownBuffer();
  function normalizedSlotLevel(buffer){let square=0,peak=0,count=0;for(let ch=0;ch<buffer.numberOfChannels;ch++){const data=buffer.getChannelData(ch),step=Math.max(1,Math.floor(data.length/12000));for(let i=0;i<data.length;i+=step){const sample=data[i];square+=sample*sample;peak=Math.max(peak,Math.abs(sample));count++}}const rms=Math.sqrt(square/Math.max(1,count));return Math.min(.82,.76/Math.max(.01,peak),.115/Math.max(.01,rms))}
  startSpinSound=()=>{
    let stopped=false,spinSource=null,spinGain=null,slowSource=null,slowGain=null;
    const fadeOut=(source,gain,seconds=.16)=>{if(!source||!gain)return;try{const now=audio().currentTime;gain.gain.cancelScheduledValues(now);gain.gain.setValueAtTime(Math.max(.001,gain.gain.value),now);gain.gain.exponentialRampToValueAtTime(.001,now+seconds);source.stop(now+seconds+.03)}catch{}};
    Promise.all([loadRouletteSpinBuffer(),loadSlowdownBuffer()]).then(([spinBuffer,slowBuffer])=>{
      if(stopped||!spinBuffer)return;
      const ctx=audio(),start=ctx.currentTime+.015,slowStart=start+3.98,fadeDuration=.38,spinLevel=normalizedSlotLevel(spinBuffer),slowLevel=slowBuffer?normalizedSlotLevel(slowBuffer):0;
      spinSource=ctx.createBufferSource();spinGain=ctx.createGain();spinSource.buffer=spinBuffer;spinSource.loop=true;spinSource.loopStart=.015;spinSource.loopEnd=Math.max(.02,spinBuffer.duration-.02);spinGain.gain.setValueAtTime(.001,start);spinGain.gain.linearRampToValueAtTime(spinLevel,start+.055);spinSource.connect(spinGain).connect(ctx.destination);spinSource.start(start);
      if(!slowBuffer)return;
      // 同じ実効音量へ正規化した2音源を重ね、回転音が途切れないまま減速音へ移す。
      spinGain.gain.setValueAtTime(spinLevel,slowStart);spinGain.gain.linearRampToValueAtTime(.001,slowStart+fadeDuration);
      slowSource=ctx.createBufferSource();slowGain=ctx.createGain();slowSource.buffer=slowBuffer;slowGain.gain.setValueAtTime(.001,slowStart);slowGain.gain.linearRampToValueAtTime(slowLevel,slowStart+fadeDuration);slowSource.connect(slowGain).connect(ctx.destination);slowSource.start(slowStart,.012);
    });
    return()=>{if(stopped)return;stopped=true;fadeOut(spinSource,spinGain);fadeOut(slowSource,slowGain)};
  };

  // フィルターに合わせ、回す前の3リールにも対象店舗だけを表示する。
  seedInitialSlot=()=>{
    const stage=$('#slot-stage');if(spinning||stage?.classList.contains('is-jackpot'))return;
    const pool=selectedFilter==='all'?shops:shops.filter(s=>s.status===selectedFilter),reels=$$('.slot-reel');if(!reels.length)return;
    let picks=[];
    if(pool.length>=3){const shuffled=[...pool];for(let i=shuffled.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[shuffled[i],shuffled[j]]=[shuffled[j],shuffled[i]]}picks=shuffled.slice(0,3)}
    else if(pool.length){const pick=pool[Math.floor(Math.random()*pool.length)];picks=[pick,pick,pick]}
    reels.forEach((reel,index)=>{reel.style.transition='none';reel.style.willChange='auto';reel.style.transform='translate3d(0,0,0)';reel.innerHTML=`<div class="reel-item">${picks[index]?esc(picks[index].name):'店舗を登録'}</div>`});
  };
  function resetSlotResultView(){const stage=$('#slot-stage'),result=$('#slot-result');stage.classList.remove('is-jackpot','is-jackpot-prelude','is-jackpot-complete');result.classList.add('hidden');result.classList.remove('with-photo');$('#result-map-btn').classList.add('hidden');$('#gacha-message').textContent=''}
  $$('.filter').forEach(button=>button.onclick=()=>{if(spinning)return;$$('.filter').forEach(x=>x.classList.toggle('active',x===button));selectedFilter=button.dataset.filter;lastResult=null;resetSlotResultView();seedInitialSlot()});

  // 各ロール停止で確実に停止音を鳴らし、最後の停止後は一度だけ当選演出へ移る。
  reelStopSound=()=>{
    playReelStopSound();jackpotReelStops++;if(jackpotReelStops!==3)return;
    const sequence=++jackpotSequence,stage=$('#slot-stage'),spinButton=$('#spin-btn');stage.classList.add('is-jackpot-prelude');startFrameWhine();$('#result-map-btn').classList.add('hidden');
    setTimeout(()=>{if(sequence!==jackpotSequence)return;spinning=true;spinButton.disabled=true;$('#result-map-btn').classList.add('hidden')},505);
    setTimeout(()=>{if(sequence!==jackpotSequence)return;stopFrameWhine();stage.classList.remove('is-jackpot-prelude');stage.classList.add('is-jackpot');jackpotSound()},2000);
    setTimeout(()=>{if(sequence!==jackpotSequence)return;stage.classList.add('is-jackpot-complete');spinning=false;spinButton.disabled=false;$('#result-map-btn').classList.remove('hidden')},4250);
  };
  clickSound=()=>{jackpotSequence++;jackpotReelStops=0;stopFrameWhine();stopDoorRevealSound();$('#slot-stage').classList.remove('is-jackpot','is-jackpot-prelude','is-jackpot-complete');$('#confetti').replaceChildren();tone(680,.06,'triangle',.045)};

  if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js?v=91').catch(()=>{}));bootPromise=boot();
})();
